name: Build WebVM with Claude CLI

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build container and export rootfs
        run: |
          docker build -t claude-vm .
          container_id=$(docker create claude-vm)
          docker export $container_id -o rootfs.tar
          mkdir rootfs
          tar -xf rootfs.tar -C rootfs

      - name: Create ext2 disk image
        run: |
          sudo apt-get update && sudo apt-get install -y e2fsprogs
          dd if=/dev/zero of=disk.img bs=1M count=2048
          mkfs.ext2 -F disk.img
          mkdir mnt
          sudo mount -o loop disk.img mnt
          sudo cp -a rootfs/* mnt/
          sudo umount mnt

      - name: Prepare public folder
        run: |
          mkdir public
          mv disk.img public/
          cp index.html config.js public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
